### ISSUE TITLE
Choose another naming strategy, which does not conflict with the standard "Show"

### ISSUE THREAD

**Issue by nikita-volkov** [RyanGlScott/text-show#10]
While we all agree that the `String` and the standard `Show` are suboptimal, they are still used for a huge amount of tasks, which "text-show" does not approach. Take, for instance, `traceShow` - to be able to use it my types need to derive the standard `Show`, but this leaves me with a requirement of some nasty import business due to conflicts of Prelude and "text-show". Also there's still plenty of cases when I need to use the standard "Show", since there are tons of standard libraries, which are targetted at `String`.

I strongly believe that not pretending to replace the standard `Show` will make the library both more useful and used.

Hence, I propose to remove the conflicts with the standard Prelude, by renaming the appropriate entities into something different. E.g., `Show`, `show` and etc.

**Comment by RyanGlScott** [comment]
I'm not opposed to this in principle—I've been meaning to change the `Text.Show.Text` top-level prefix to `TextShow` for a while anyways, so I suppose I should go the whole nine yards and disambiguate text `Show` from string `Show`.

My question to you is: which names in particular are giving you trouble? Currently, my naming scheme is (roughly) as follows:

1. Typeclasses: `Show`, `Show1`, `Show2`, `GShow`, and `GShow1`
2. Data types: `FromStringShow` and `FromTextShow`
3. Functions: three categories:
 * `Builder`-based: either being with `showb` or end with the `-B` suffix
 * Strict `Text`-based: same naming conventions as string `Show`
 * Lazy `Text`-based: end with `-Lazy` suffix

**Comment by nikita-volkov** [comment]
So far, the names that were causing troubles for me were `Show` and `show`.

**Comment by RyanGlScott** [comment]
Alright. In that case, I think I'll rename the following:

* `Show` to `TextShow` (and similarly for other typeclasses)
* Add the `-Text` suffix to everything that returns a strict `Text` value (so `show` would become `showText`, etc.)
* Add the `-LazyText` to everythibg that returns a lazy `Text` value (so `showLazy` would become `showLazyText`, etc.)

With that, I think it should be possible to use `TextShow` and string `Show` simultaneously without qualified imports. Does that sound agreeable?

**Comment by nikita-volkov** [comment]
> Does that sound agreeable?

Absolutely! Thank you.

---

As a side-note, how about changing `showb` to `showTextBuilder` (or `showBuilder`) to accommodate to the others stylistically? In case you're looking for shortcuts, you could also introduce something like `showST`, `showLT`, `showTB` as aliases.

**Comment by RyanGlScott** [comment]
For brevity's sake, I think it would make the most sense to keep the `Builder`-related functions suffixed with `-b` (also since string `Show` [uses a similar convention](http://hackage.haskell.org/package/base-4.8.0.0/docs/Prelude.html#v:shows) with `ShowS`). To make things a little more uniform, I could put a `-T` and `-TL` suffix to indicate strict- and lazy-`Text`–producing functions.

**Comment by RyanGlScott** [comment]
This should be fixed as of [`text-show-2`](http://hackage.haskell.org/package/text-show-2). I also added a [wiki article](https://github.com/RyanGlScott/text-show/wiki/Naming-conventions) that elaborates more on the new naming conventions.

**Comment by nikita-volkov** [comment]
Thank you!
