### ISSUE TITLE
Orphan Instances mess up haddocks

### ISSUE THREAD

**Issue by andrewthad** [RyanGlScott/text-show#18]
Since almost all of the `TextShow` instances are provided as orphans, the don't show up in the haddocks. This is similar to an [issue in aeson](https://github.com/bos/aeson/issues/375) that I noticed.

**Comment by RyanGlScott** [comment]
I'm 99% sure this is a GHC bug. My reasoning stems from the discussion [here](https://github.com/ku-fpg/hermit/issues/173), since someone else had trouble looking up orphan instances with the GHC API.

**Comment by RyanGlScott** [comment]
I'm going to close this issue, since I'm not willing to refactor huge chunks of this library to accommodate what is a proper Haddock bug. See my comment [here](https://github.com/haskell/haddock/issues/372#issuecomment-239469918).

**Comment by RyanGlScott** [comment]
This issue has been fixed upstream in Haddock, and will land in the Haddock bundled with GHC 8.4.1. Proof:

![haddock](https://user-images.githubusercontent.com/2364661/35779054-2351431a-0995-11e8-8eb5-c539d4e3c8d2.png)
