### ISSUE TITLE
Building of documentation fails, if --ignore-all-exports flag is set

### ISSUE THREAD

**Issue by marcellussiegburg** [RyanGlScott/text-show#32]
Building the haddock documentation fails, if the --ignore-all-exports flag is set when calling haddock. The given erroneous output is:

```
    haddock: internal error: renameType: HsSpliceTy
    CallStack (from HasCallStack):
      error, called at utils/haddock/haddock-api/src/Haddock/Interface/Rename.hs:267:30 in main:Haddock.Interface.Rename
```

**Comment by RyanGlScott** [comment]
This is a [Haddock bug](https://github.com/haskell/haddock/issues/574). It was fixed in https://github.com/haskell/haddock/pull/745, so this should work on GHC 8.4.1.
