### ISSUE TITLE
Property test failure for version 3.7.1

### ISSUE THREAD

**Issue by Gabriel439** [RyanGlScott/text-show#36]
```
Failures:

  tests/Spec/Utils.hs:47:
  1) Spec.Foreign.C.Types.CClock TextShow instance
       uncaught exception: ErrorCall (Enum.fromEnum{Word64}: value (18446744073709551615) is outside of Int's bounds (-9223372036854775808,9223372036854775807)) (after 1 test)
       *** Failed! Exception while generating shrink-list: 'Enum.fromEnum{Word64}: value (18446744073709551615) is outside of Int's bounds (-9223372036854775808,9223372036854775807)' (after 1 test):
       0
       Exception thrown while showing test case: 'Enum.fromEnum{Word64}: value (18446744073709551615) is outside of Int's bounds (-9223372036854775808,9223372036854775807)'

Randomized with seed 1188900471

Finished in 0.9938 seconds
395 examples, 1 failure
Test suite spec: FAIL
```

**Comment by RyanGlScott** [comment]
Urk, platform differences strike again. This works on my machine since it treats `CClock` as an `Int64` (which fits into an `Int`), but not on your machine, which treats `CClock` as a `Word64` (which doesn't fit into an `Int`). This is due to https://github.com/nick8325/quickcheck/issues/201, the [fix for which](https://github.com/nick8325/quickcheck/commit/033cc9bac2c98a88028427e316621dce6d432f2c) hasn't made it into a Hackage release yet.

I can see two different ways forward:

1. Disable the `CClock` tests entirely until a new version of `QuickCheck` is released with a working `Arbitrary` instance for `CClock`.
2. Define a newtype wrapper around `CClock` with a proper `Arbitrary` instance and use that temporarily.

**Comment by Gabriel439** [comment]
Yeah, I'm not blocked on this at the moment (I can just disable the test suite) so I'd be fine just waiting for a new version of `QuickCheck` if that's simpler

**Comment by RyanGlScott** [comment]
Out of sheer curiosity, is Nix motivating this? I've had a couple of people file issues in this vein, and I've always wondered what was compelling them to scour test suites so thoroughly :)

**Comment by Gabriel439** [comment]
Yes, this is definitely a Nix thing.  Nix builds test suites by default

There are lots of packages on Hackage with technical debt in their test suites, such as:

* test suites that hang forever
* test suites that don't build or have bounds issues
* test suites that lead to cyclic dependency chains

You can see several examples of Nix's work-arounds for these issues here:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/configuration-common.nix

**Comment by RyanGlScott** [comment]
Ah, interesting. Would it suffice for Nix's purposes to just provide a patch that can be applied on top of the latest `text-show` release, then? Or would the changes need to be present in an actual Hackage release?

**Comment by RyanGlScott** [comment]
I've just pushed https://github.com/RyanGlScott/text-show/commit/1ee6beff85c159dc1dfca5baf160b9e607a05901, which I think should work around this issue. Can you confirm that it works for you?

**Comment by Gabriel439** [comment]
I verified that applying that commit as a  patch fixes the test failure

**Comment by RyanGlScott** [comment]
Great! So if I understand this correctly, this is all that needs to be done on `text-show`'s end for the time being, right?

I'll keep this issue open as a reminder to remove this hack once a new version of `QuickCheck` has been released.

**Comment by Gabriel439** [comment]
Yes, that's correct

**Comment by RyanGlScott** [comment]
NB: Commit 1ee6beff85c159dc1dfca5baf160b9e607a05901 is now present on Hackage in `text-show-3.7.4`.

**Comment by Gabriel439** [comment]
@RyanGlScott: Thank you! :slightly_smiling_face:
