### ISSUE TITLE
Support for `Data.Text.Lazy`

### ISSUE THREAD

**Issue by mrkkrp** [RyanGlScott/text-show#4]
Is there some way to use your library with `Data.Text.Lazy`?

**Comment by RyanGlScott** [comment]
Sure! The class methods of `Show` all return `Builder`s, so they can be converted easily to either strict or lazy `Text`. The `Text.Show.Text` module defines a [`showLazy`](http://hackage.haskell.org/package/text-show-0.7/docs/Text-Show-Text.html#v:showLazy) function which converts a `Show` instance to a lazy `Text`.

**Comment by mrkkrp** [comment]
Glad to hear! Thank you, I think I should close the issue.
