### ISSUE TITLE
Does not build on GHCJS

### ISSUE THREAD

**Issue by Saulzar** [RyanGlScott/text-show#40]
Is it meant to? (ghcjs 0.2.0, ghc 8.0.2)

src/TextShow/Data/Text.hs:25:1: error:
    Failed to load interface for ‘Data.Text.Foreign’

**Comment by RyanGlScott** [comment]
Hi @Saulzar. I've never been able to successfully build `text-show` with GHCJS (or most large Haskell projects, for that matter), so I'm certainly not surprised to learn that `text-show` doesn't build with GHCJS. If you know how to fix the issue, I'd gladly accept a patch.

**Comment by RyanGlScott** [comment]
OK, with the help of the folks at the #ghcjs IRC channel, I was able to get further than before. In fact, I was able to build the entirety of `text-show-3.7.4` (the library, at least) with `ghcjs-8.4.0.1`, so perhaps this is simply an issue with an old version of `ghcjs`? This means I'd likely need to patch around the issue with some sort of CPP, but I don't know what that would be. If anyone reading this is familiar with `ghcjs` and knows the answer, your input would be appreciated.

**Comment by Saulzar** [comment]
Hmm. I don't quite understand the error, maybe it's got nothing to do with text-show. Looks like that module should be present - but the interface files are missing in my environment (I'm using the reflex-platform).

In this enviornment the text version is 1.2.2.1 which definitely has this module, and I can import it just fine compiling with ghcjs --make.

**Comment by tgass** [comment]
I managed to build a project using text-show without any problems using stack and ghcjs-0.2.1.9008011_ghc-8.0.2. But as I'm switching to reflex-platform I ran into the described problem as well. So I'd assume it's a problem on the reflex-platform side.

**Comment by tgass** [comment]
There's now an issue in the reflex-platform project: https://github.com/reflex-frp/reflex-platform/issues/466

**Comment by RyanGlScott** [comment]
OK. I'm not familiar with how `reflex-platform` does things. Is the necessary patching that has to be done to `text-show` something that can be upstreamed into this repo?

**Comment by tgass** [comment]
My current understanding is that nothing needs to be done in text-show but only in reflex-platform. text-show as it is compiles with ghcjs.

reflex-platform (when used with ghcjs) uses a fork of the text package that doesn't expose Data.Text.Foreign. And within reflex-platform there is already a place to adjust packages that are dependent on the forked text package. I'm currently looking into this and hopefully get a PR ready soon.

**Comment by RyanGlScott** [comment]
Are these patches tied to particular Hackage releases? My concern is that as `text-show` makes new releases, this `reflex-platform` patch will quickly become out-of-date and have to be maintained separately.

**Comment by tgass** [comment]
Here is the PR I made for reflex-platform (https://github.com/reflex-frp/reflex-platform/pull/468). Ryan from the reflex project is asking if you'd be interested in taken it. Maybe just have a look.

**Comment by ryantrinkle** [comment]
@RyanGlScott I think it's really on reflex-platform to make this work, but if you would be willing to have a flag that chops out the Foreign stuff, that would definitely make our lives easier!

For what it's worth, the reason we use a non-standard `text` package is that, in our test cases, it saved almost 50% of the total memory of a running program compared with the standard `text` implementation.  Browsers are *much* better at dealing with their own strings than at letting us reimplement them in terms of typed buffers!

**Comment by RyanGlScott** [comment]
Judging from the patch, it looks like the only part that's giving `reflex-platform` trouble is the `I16` instance? To be honest, I have no particular reason for having that; I just blindly added it in an attempt to provide a `TextShow` instance to mirror every publicly accessible `Show` instance in the `text`. But `I16` is really an internal component of `text`, and given a choice between workaround around the issue with CPP and just removing the `I16` stuff altogether from `text-show`, I'm inclined to pick the latter (and wait until someone complains before adding it back). Does that sound like a reasonable course of action?

**Comment by ryantrinkle** [comment]
@RyanGlScott Thanks!  I really appreciate you sorting this out :)

@tgass Want to strip out the patch in reflex-platform?

**Comment by tgass** [comment]
@ryantrinkle Sure. I'll just revert the commit and open a PR.

**Comment by RyanGlScott** [comment]
I've uploaded [`text-show-3.8`](http://hackage.haskell.org/package/text-show-3.8) to Hackage with these changes.

**Comment by ryantrinkle** [comment]
@RyanGlScott Awesome; thanks!
