### ISSUE TITLE
Support for Data.Text.Short.ShortText

### ISSUE THREAD

**Issue by Boarders** [RyanGlScott/text-show#42]
Would it be possible to add an instance for ShortText from Data.Text.Short? It is a newtype wrapper around a ShortByteString which has an existing instance.

**Comment by RyanGlScott** [comment]
I assume that you're referring to the [`text-short`](http://hackage.haskell.org/package/text-short) package? I foresee a couple of issues with this.

One is that `text-show`'s support window currently extends back to `base-4.5` (GHC 7.4), whereas `text-short` only supports `base-4.7` (GHC 7.8) and later. I'm not inherently opposed to dropping support for GHC 7.4 or 7.6 (I generally support as far back as I can within reasonable limits), but I'm not sure that I want to do so just for the sake of a single dependency. I'd also need to make sure that no downstream users of `text-show` would be affected by this narrower support window.

Another issue is whether supporting `text-short` is within the scope of the `text-show` package or not. I've (somewhat arbitrarily) deemed that the libraries that `text-show` will provide instances for are `array`, `base`, `bytestring`, and `text`, and that any other dependencies that `text-show` might incur will either be (1) to support older versions of GHC (e.g., `tagged` and `void`) or (2) to support the Template Haskell machinery (e.g., `th-abstraction`). `text-short` doesn't really fit into this mold, which makes me somewhat hesitant.

For the reasons above, I'm somewhat leaning towards the "no" side. That being said, I do have a [`text-show-instances`](http://hackage.haskell.org/package/text-show-instances) package which adds instances for several external packages, and I'd be much more willing to narrow its support window if need be to add support for `text-short`. If you'd find that useful and would be willing to make a pull request to `text-show-instances`, I'd be happy to accept it.

Alternatively, if several other peiple chime in clamoring for `text-short` support in `text-show`, I could be persuaded to add it. But I'm not entirely convinced at the moment that it's worth it.

**Comment by Boarders** [comment]
That all makes sense. I'll work up a pull request for text-show-instances. Thanks for getting back to me so promptly.

**Comment by RyanGlScott** [comment]
Sounds good. Since you've made a separate pull request in the `text-show-instances` repo ([here](https://github.com/RyanGlScott/text-show-instances/pull/10)), I'll go ahead and close this issue in favor of that PR.
