### ISSUE TITLE
Not in lts-13.0

### ISSUE THREAD

**Issue by googleson78** [RyanGlScott/text-show#43]
Any particular reason for this? It seems to compile (and pass all the tests) with `lts-13.0` just fine.
Is there anything to do before adding it to 13.*? Excuse me if this is not the right place/way to ask for this.

**Comment by RyanGlScott** [comment]
Urgh. This _used_ to be in Stackage nightly, but it seems to have been held back for some unknown reason (moreover, I wasn't notified that it was held back). I've opened https://github.com/commercialhaskell/stackage/pull/4254 to add it back, so I'll close this issue in favor of that one.

**Comment by googleson78** [comment]
Thanks! :)

**Comment by janpath** [comment]
You also have to open an issue on the [lts-haskell repo](https://github.com/commercialhaskell/lts-haskell/issues) to add it to LTS-13. It would have been added automatically if it was in the nightlies when LTS-13 launched, but now this has to be done manually.

**Comment by RyanGlScott** [comment]
Sigh. I really don't have the energy to chase down Stackage-related loose ends like this. I'd happily welcome anyone who wishes to pursue this, however.

**Comment by janpath** [comment]
Sure, I will take care of it.
