### ISSUE TITLE
#performance #question

### ISSUE THREAD

**Issue by howsiwei** [RyanGlScott/text-show#44]
```
instance TextShow TL.Text where
    showb = showbString . TL.unpack
```
Above is how `instance TextShow TL.Text` is defined in `TextShow.Data.Text` It's probably inefficient to convert `TL.Text` to `String` first before converting it to `Builder`. Why not use `fromLazyText` defined in `Data.Text.Lazy.Builder`? The sames goes to `TS.Text`.

**Comment by RyanGlScott** [comment]
`fromLazyText` isn't a correct implementation of `showb`, since it doesn't escape characters that it needs to. For instance, `showbString (unpack ("foo" :: Text))` produces `"\"foo\""`, whereas `fromLazyText ("foo" :: Text)` produces `"foo"`.

Does that answer your question?

**Comment by howsiwei** [comment]
You're right. It's not easy to do better than `showbString . unpack` considering how complicated the escaping rules are.
