### ISSUE TITLE
Vector support

### ISSUE THREAD

**Issue by flip111** [RyanGlScott/text-show#62]
Could an instance for `instance TextShow a => TextShow (Vector a)` be added?

**Comment by RyanGlScott** [comment]
From the [package description](https://github.com/RyanGlScott/text-show/blob/e41272b370c5081a90781cd9024be1b800c8239f/text-show.cabal#L9-L13), `text-show` only provides `TextShow` instances for data types in the `array`, `base`, `bytestring`, and `text` packages in an effort to keep the dependency footprint relatively minimal. I have a separate [`text-show-instances`](https://hackage.haskell.org/package/text-show-instances) package with a broader set of dependencies that includes `TextShow` instances for `vector` types.

**Comment by flip111** [comment]
Thank you @RyanGlScott is text-show-instances somewhere mentioned in text-show? i didn't knew about it.

**Comment by RyanGlScott** [comment]
Hm, I thought I had mentioned `text-show-instances` in the `README`, but it appears that I don't. I'll prepare a patch to clarify that.
