### ISSUE TITLE
text-show-0.8 does not compile

### ISSUE THREAD

**Issue by peti** [RyanGlScott/text-show#8]
Citing from http://hydra.cryp.to/build/840755/nixlog/2/raw:

~~~~~~
tests/Instances/Numeric/Natural.hs:18:40:
    Module ‘Test.QuickCheck’ does not export ‘arbitrarySizedNatural’
~~~~~~~

**Comment by RyanGlScott** [comment]
One of these days, I'm going to put out a major version bump without something breaking :)

Thanks for the heads up. I've released [`text-show-0.8.1`](http://hackage.haskell.org/package/text-show-0.8.1) on Hackage, which should build with older versions of `QuickCheck`.
